### PR TITLE
add support for metadata

### PR DESCRIPTION
**Pull request by thorinaboenke**
This PR relates to issue #76 - 
adds support for metadata in logging to attackmate.log

- create custom adapter to add extra argument metadata to logger
- add optional attribute "metadata" to BaseCommand class
- adapt logging in commands to include metadata

### CODE REVIEW

**Comment by thorinaboenke** [comment]
sry about the reformatting changes; can someone please share their formatter settings with me?

**Comment by whotwagner** [comment]
I'd prefer the metadata of the schema as an optional list of key-value-pairs. We will also add support for other output-formats like json in future. With key-value-pairs we can then format and handle that part better.

**Comment by thorinaboenke** [comment]
Could you clarify the requirements how that should look in a playbook and in the logging? (Or is the logging irrelevant for this issue?)

**Comment by whotwagner** [comment]
The metadata should be defined in a list of key-value pairs like following:

```yaml
- type: shell
  cmd: nmap localhost
  metadata:
    - command: nmap
    - host: localhost
    - type: scan
```

We will then include function "log_meta" to the base_command-class that log.info the metadata as a json-string only if the metadata of a command is defined. After that, we have 2 types of output in attackmate.log:

1. Command Execution performed by log_command()
2. MetaData performed by log_meta

Since these log-outputs are in different lines, this isn't really machine-readable. For that we will later also include a seperate json-output that can be activated by a commandline-parameter ( Issue #103 )

**Pull request closed without merging**
